"""
Canonical configuration registry for the IBKR trading system.

This registry is the single source of truth for configuration variables,
including defaults, environment overrides, and subsystem ownership.
"""

from __future__ import annotations

from datetime import time
from pathlib import Path
from typing import Any, Dict


def _default_verified_rss_path() -> str:
    return str(Path("verified_rss.txt"))


def _default_git_sha() -> str | None:
    return None


def _scanner_session_windows_utc() -> Dict[str, float]:
    return {
        "PRE_START": 12.0,
        "RTH_START": 14.0,
        "AFT_START": 21.5,
        "AFT_END": 23.0,
    }


def _market_session_windows_local() -> Dict[str, time]:
    return {
        "PRE_START": time(4, 0),
        "REGULAR_START": time(9, 30),
        "REGULAR_END": time(16, 0),
        "AFTER_END": time(20, 0),
    }


CONFIG_REGISTRY: Dict[str, Dict[str, Any]] = {
    # =========================
    # Runtime modes & safety
    # =========================
    "RUN_MODE": {
        "type": str,
        "default": "LIVE",
        "env": ["RUN_MODE"],
        "affects": ["CoreOrchestrator", "ExecutionEngine", "Scanner", "StorageEngine"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Baseline runtime mode before safety-derived overrides.",
        "choices": ["SIM", "PAPER", "LIVE", "LIVE_READ_ONLY", "LIVE_MICRO", "LIVE_ONE_SHARE"],
        "normalizer": "upper",
    },
    "RUN_MODE_EFFECTIVE": {
        "type": str,
        "default": None,
        "env": [],
        "affects": ["CoreOrchestrator", "ExecutionEngine", "Scanner"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Derived run mode after safety rules (LIVE_READ_ONLY override).",
        "choices": ["SIM", "PAPER", "LIVE", "LIVE_READ_ONLY", "LIVE_MICRO", "LIVE_ONE_SHARE"],
        "normalizer": "upper",
        "derived": True,
    },
    "EVENT_REPLAY_MODE": {
        "type": str,
        "default": "CYCLE",
        "env": ["EVENT_REPLAY_MODE"],
        "affects": ["CoreOrchestrator", "ReplayEngine", "StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Requested event replay mode before live safety overrides.",
        "choices": ["OFF", "CYCLE", "RUN"],
        "normalizer": "upper",
    },
    "EVENT_REPLAY_MODE_EFFECTIVE": {
        "type": str,
        "default": None,
        "env": [],
        "affects": ["CoreOrchestrator", "ReplayEngine"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Derived event replay mode (forced OFF in live modes).",
        "choices": ["OFF", "CYCLE", "RUN"],
        "normalizer": "upper",
        "derived": True,
    },
    "EXECUTION_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["EXECUTION_ENABLED"],
        "affects": ["ExecutionEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Legacy execution enable flag (execution is now derived from RUN_MODE).",
    },
    "EXECUTION_ENABLED_EFFECTIVE": {
        "type": bool,
        "default": None,
        "env": [],
        "affects": ["ExecutionEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Derived execution enable flag after run-mode safety rules.",
        "derived": True,
    },
    "LIVE_MICRO_ACK": {
        "type": bool,
        "default": False,
        "env": ["LIVE_MICRO_ACK"],
        "affects": ["ExecutionEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Explicit acknowledgement required for LIVE_MICRO execution.",
    },
    "LIVE_MICRO_1_SHARE_ONLY": {
        "type": bool,
        "default": True,
        "env": ["LIVE_MICRO_1_SHARE_ONLY"],
        "affects": ["ExecutionEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Limit LIVE_MICRO to 1-share orders only.",
    },
    "LIVE_MICRO_MAX_CONCURRENT_TRADES": {
        "type": int,
        "default": 1,
        "env": ["LIVE_MICRO_MAX_CONCURRENT_TRADES"],
        "affects": ["ExecutionEngine", "RiskEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Max concurrent trades allowed in LIVE_MICRO.",
    },
    "LIVE_MICRO_MAX_TRADES_PER_DAY": {
        "type": int,
        "default": 3,
        "env": ["LIVE_MICRO_MAX_TRADES_PER_DAY"],
        "affects": ["ExecutionEngine", "RiskEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Max trades per day allowed in LIVE_MICRO.",
    },
    "LIVE_MICRO_MAX_DAILY_LOSS": {
        "type": float,
        "default": 5.0,
        "env": ["LIVE_MICRO_MAX_DAILY_LOSS", "LIVE_MICRO_DAILY_MAX_LOSS"],
        "affects": ["ExecutionEngine", "RiskEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Daily max loss circuit breaker for LIVE_MICRO.",
    },
    "RISK_PROFILE": {
        "type": str,
        "default": "NORMAL",
        "env": ["RISK_PROFILE"],
        "affects": ["RiskEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Risk profile name applied at the intent-to-order boundary.",
        "choices": ["NORMAL", "MICRO", "SMALL"],
        "normalizer": "upper",
    },
    "RISK_ACCOUNT_EQUITY": {
        "type": float,
        "default": 100000.0,
        "env": ["RISK_ACCOUNT_EQUITY"],
        "affects": ["RiskEngine", "PerformanceRegistry"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Reference account equity for risk-profile percentage caps.",
    },
    "IBKR_READONLY_ENABLED": {
        "type": bool,
        "default": True,
        "env": ["IBKR_READONLY_ENABLED"],
        "affects": ["MarketDataHub", "ExecutionEngine", "IBKR"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "If true, IBKR order routing is blocked system-wide.",
    },
    "IBKR_API_WRITE_ALLOWED": {
        "type": bool,
        "default": True,
        "env": ["IBKR_API_WRITE_ALLOWED"],
        "affects": ["CoreOrchestrator", "IBKR"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Allow write access to IBKR API (used for live read-only override).",
    },
    "INTENT_DEDUP_SELFTEST_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["INTENT_DEDUP_SELFTEST_ENABLED"],
        "affects": ["CoreOrchestrator"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Enable self-test to deduplicate intents during normalization.",
    },
    # =========================
    # Adaptive regime layer
    # =========================
    "ADAPTIVE_REGIME_LAYER_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["ADAPTIVE_REGIME_LAYER_ENABLED"],
        "affects": ["RegimeLayer", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Enable the adaptive regime/microstructure layer.",
    },
    "ADAPTIVE_REGIME_POLICY_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["ADAPTIVE_REGIME_POLICY_ENABLED"],
        "affects": ["RegimeLayer", "StrategyRunner", "RiskEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Enable regime policy application (weights/eligibility/risk multipliers).",
    },
    "ADAPTIVE_REGIME_MIN_CONFIDENCE_TO_APPLY": {
        "type": float,
        "default": 0.65,
        "env": ["ADAPTIVE_REGIME_MIN_CONFIDENCE_TO_APPLY"],
        "affects": ["RegimePolicy"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Minimum regime confidence required to apply policy decisions.",
    },
    "ADAPTIVE_REGIME_STRATEGY_WEIGHTING_MODE": {
        "type": str,
        "default": "OFF",
        "env": ["ADAPTIVE_REGIME_STRATEGY_WEIGHTING_MODE"],
        "affects": ["RegimePolicy", "StrategyRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Policy mode for strategy adaptation: OFF, WEIGHT, ENABLE_DISABLE.",
        "choices": ["OFF", "WEIGHT", "ENABLE_DISABLE"],
        "normalizer": "upper",
    },
    "ADAPTIVE_REGIME_MAX_RISK_MULTIPLIER": {
        "type": float,
        "default": 1.0,
        "env": ["ADAPTIVE_REGIME_MAX_RISK_MULTIPLIER"],
        "affects": ["RegimePolicy", "RiskEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Upper bound on regime-driven risk multiplier.",
    },
    "ADAPTIVE_REGIME_MIN_RISK_MULTIPLIER": {
        "type": float,
        "default": 0.25,
        "env": ["ADAPTIVE_REGIME_MIN_RISK_MULTIPLIER"],
        "affects": ["RegimePolicy", "RiskEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Lower bound on regime-driven risk multiplier.",
    },
    "ADAPTIVE_REGIME_ALLOWED_SESSIONS": {
        "type": list,
        "item_type": str,
        "default": ["RTH"],
        "env": ["ADAPTIVE_REGIME_ALLOWED_SESSIONS"],
        "affects": ["RegimeLayer", "RegimePolicy"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Market sessions in which the regime policy is allowed to apply.",
        "normalizer": "upper",
    },
    "ADAPTIVE_REGIME_FEATURE_SET": {
        "type": str,
        "default": "BASIC",
        "env": ["ADAPTIVE_REGIME_FEATURE_SET"],
        "affects": ["RegimeObservers"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Feature set selection for regime observers.",
        "choices": ["BASIC", "EXTENDED"],
        "normalizer": "upper",
    },
    "ADAPTIVE_REGIME_BASELINE_WINDOW": {
        "type": int,
        "default": 60,
        "env": ["ADAPTIVE_REGIME_BASELINE_WINDOW"],
        "affects": ["BaselineStore"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Rolling window length for regime baselines.",
    },
    "ADAPTIVE_REGIME_EWMA_ALPHA": {
        "type": float,
        "default": 0.2,
        "env": ["ADAPTIVE_REGIME_EWMA_ALPHA"],
        "affects": ["BaselineStore"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "EWMA alpha for regime baseline smoothing.",
    },
    "ADAPTIVE_REGIME_LOG_LEVEL": {
        "type": str,
        "default": "INFO",
        "env": ["ADAPTIVE_REGIME_LOG_LEVEL"],
        "affects": ["RegimeLayer"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Log level for regime outputs.",
        "choices": ["DEBUG", "INFO", "WARN", "ERROR"],
        "normalizer": "upper",
    },
    "ADAPTIVE_REGIME_ALLOWED_RISK_MULTIPLIERS": {
        "type": list,
        "item_type": float,
        "default": [0.0, 0.25, 0.5, 0.75, 1.0],
        "env": ["ADAPTIVE_REGIME_ALLOWED_RISK_MULTIPLIERS"],
        "affects": ["RegimePolicy"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Allowed risk multiplier values for regime policy.",
    },
    "ADAPTIVE_REGIME_ALLOWED_STRATEGY_WEIGHTS": {
        "type": list,
        "item_type": float,
        "default": [0.0, 0.25, 0.5, 0.75, 1.0],
        "env": ["ADAPTIVE_REGIME_ALLOWED_STRATEGY_WEIGHTS"],
        "affects": ["RegimePolicy", "StrategyRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Allowed strategy weight values for regime policy.",
    },
    # =========================
    # IBKR connectivity & market data
    # =========================
    "IBKR_HOST": {
        "type": str,
        "default": "127.0.0.1",
        "env": ["IBKR_HOST"],
        "affects": ["IBKR", "MarketDataHub", "StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "IBKR gateway host.",
    },
    "IBKR_PORT": {
        "type": int,
        "default": 7497,
        "env": ["IBKR_PORT"],
        "affects": ["IBKR", "MarketDataHub", "StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "IBKR gateway port.",
    },
    "IBKR_CLIENT_ID": {
        "type": int,
        "default": 7,
        "env": ["IBKR_CLIENT_ID"],
        "affects": ["IBKR", "MarketDataHub", "Scanner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "IBKR client ID for market data connections.",
    },
    "IBKR_MARKET_DATA_TYPE": {
        "type": str,
        "default": "DELAYED",
        "env": ["IBKR_MARKET_DATA_TYPE"],
        "affects": ["MarketDataHub", "Scanner", "StorageEngine"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "IBKR market data type (LIVE/DELAYED/etc).",
        "choices": ["LIVE", "DELAYED", "DELAYED_FROZEN", "FROZEN"],
        "normalizer": "upper",
    },
    "IBKR_SNAPSHOT_TIMEOUT_SECONDS": {
        "type": int,
        "default": 5,
        "env": ["IBKR_SNAPSHOT_TIMEOUT_SECONDS"],
        "affects": ["MarketDataHub", "Scanner", "IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Timeout for IBKR snapshot requests in seconds.",
    },
    "IBKR_SNAPSHOT_MAX_AGE_SECONDS": {
        "type": int,
        "default": 15,
        "env": ["IBKR_SNAPSHOT_MAX_AGE_SECONDS"],
        "affects": ["Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Maximum age of IBKR snapshot data before treated as stale.",
    },
    "IBKR_MAX_SYMBOLS_PER_CYCLE": {
        "type": int,
        "default": 50,
        "env": ["IBKR_MAX_SYMBOLS_PER_CYCLE"],
        "affects": ["MarketDataHub", "Scanner", "LiveReadOnlyScanner"],
        "enforcement": "HARD",
        "mutable": "per-cycle",
        "description": "Upper bound on symbols that may be snapshotted per cycle.",
    },
    "IBKR_FALLBACK_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["IBKR_FALLBACK_ENABLED"],
        "affects": ["Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Allow fallback scanner outputs when IBKR data is unavailable.",
    },
    "IBKR_FALLBACK_SOURCE": {
        "type": str,
        "default": "STATIC",
        "env": ["IBKR_FALLBACK_SOURCE"],
        "affects": ["Scanner", "MarketDataHub"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Label for fallback data source when IBKR unavailable.",
        "normalizer": "upper",
    },
    "IBKR_AUTO_LOCKDOWN_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["IBKR_AUTO_LOCKDOWN_ENABLED"],
        "affects": ["Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable automatic lockdown when data quality fails.",
    },
    "DEBUG_MARKET_DATA": {
        "type": bool,
        "default": False,
        "env": ["DEBUG_MARKET_DATA"],
        "affects": ["MarketDataHub", "Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Enable verbose market data diagnostics logging.",
    },
    "DEBUG_SCANNER": {
        "type": bool,
        "default": False,
        "env": ["DEBUG_SCANNER"],
        "affects": ["Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Enable verbose scanner diagnostics logging.",
    },
    "IBKR_DEFAULT_EXCHANGE": {
        "type": str,
        "default": "SMART",
        "env": ["IBKR_DEFAULT_EXCHANGE"],
        "affects": ["ExecutionEngine", "IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Default exchange for IBKR order translation.",
    },
    "IBKR_DEFAULT_CURRENCY": {
        "type": str,
        "default": "USD",
        "env": ["IBKR_DEFAULT_CURRENCY"],
        "affects": ["ExecutionEngine", "IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Default currency for IBKR order translation.",
    },
    "IBKR_ORDER_TRANSLATION_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["IBKR_ORDER_TRANSLATION_ENABLED"],
        "affects": ["ExecutionEngine", "CLI"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Enable IBKR order translation.",
    },
    "IBKR_ORDER_SUBMISSION_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["IBKR_ORDER_SUBMISSION_ENABLED"],
        "affects": ["ExecutionEngine", "CLI"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Enable IBKR order submission for live/paper.",
    },
    "IBKR_KILL_SWITCH": {
        "type": bool,
        "default": True,
        "env": ["IBKR_KILL_SWITCH"],
        "affects": ["ExecutionEngine", "CLI"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Global kill switch to block submissions.",
    },
    "IBKR_MAX_ORDERS_PER_RUN": {
        "type": int,
        "default": 1,
        "env": ["IBKR_MAX_ORDERS_PER_RUN"],
        "affects": ["ExecutionEngine", "CLI"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Maximum IBKR orders allowed per run.",
    },
    "IBKR_SUBMIT_ONLY_SYMBOL": {
        "type": str,
        "default": None,
        "env": ["IBKR_SUBMIT_ONLY_SYMBOL"],
        "affects": ["ExecutionEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "If set, only allow submissions for this symbol.",
        "allow_none": True,
        "normalizer": "upper",
    },
    "IBKR_PAPER_ONLY_ENFORCED": {
        "type": bool,
        "default": True,
        "env": ["IBKR_PAPER_ONLY_ENFORCED"],
        "affects": ["IBKR", "CLI"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Enforce paper-only routing where applicable.",
    },
    "IBKR_PAPER_HOST": {
        "type": str,
        "default": "127.0.0.1",
        "env": ["IBKR_PAPER_HOST"],
        "affects": ["IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Paper trading host for IBKR order submission.",
    },
    "IBKR_PAPER_PORT": {
        "type": int,
        "default": 7497,
        "env": ["IBKR_PAPER_PORT"],
        "affects": ["IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Paper trading port for IBKR order submission.",
    },
    "IBKR_LIVE_PORT": {
        "type": int,
        "default": 7496,
        "env": ["IBKR_LIVE_PORT"],
        "affects": ["IBKR"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Live trading port for IBKR order submission.",
    },
    "IBKR_ACK_TIMEOUT_SECONDS": {
        "type": int,
        "default": 10,
        "env": ["IBKR_ACK_TIMEOUT_SECONDS"],
        "affects": ["IBKR", "ExecutionEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Timeout for IBKR submission acknowledgements.",
    },
    "IBKR_CLIENT_ID_ORDER_SUBMIT": {
        "type": int,
        "default": 9012,
        "env": ["IBKR_CLIENT_ID_ORDER_SUBMIT"],
        "affects": ["IBKR", "CLI"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "IBKR client ID for order submission connections.",
    },
    "IBKR_GUARD_PERSIST_PATH": {
        "type": str,
        "default": "runtime/submission_guard.json",
        "env": ["IBKR_GUARD_PERSIST_PATH"],
        "affects": ["ExecutionEngine", "CLI"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Persistence path for the submission guard state.",
    },
    "DAILY_LOSS_WARNING_LIMIT": {
        "type": float,
        "default": 5.0,
        "env": ["DAILY_LOSS_WARNING_LIMIT"],
        "affects": ["RiskEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Daily loss warning threshold (absolute value).",
    },
    "DAILY_LOSS_HARD_LIMIT": {
        "type": float,
        "default": 10.0,
        "env": ["DAILY_LOSS_HARD_LIMIT"],
        "affects": ["RiskEngine", "CoreOrchestrator"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Daily loss hard stop threshold (absolute value).",
    },
    # =========================
    # Scanner controls
    # =========================
    "SCANNER_MODE": {
        "type": str,
        "default": "TEACHING",
        "env": ["SCANNER_MODE"],
        "affects": ["CoreOrchestrator", "Scanner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Scanner selection mode (TEACHING/LIVE_READONLY).",
        "choices": ["TEACHING", "LIVE_READONLY"],
        "normalizer": "upper",
    },
    "SCANNER_SYMBOLS": {
        "type": list,
        "item_type": str,
        "default": [],
        "env": ["SCANNER_SYMBOLS", "IBKR_SCAN_SYMBOLS"],
        "affects": ["Scanner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Explicit scanner symbol list (comma-separated).",
        "normalizer": "upper",
    },
    "SCANNER_DEFAULT_SYMBOLS": {
        "type": list,
        "item_type": str,
        "default": ["AAPL", "TSLA", "NVDA", "AMD", "SPY"],
        "env": [],
        "affects": ["LiveReadOnlyScanner"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "Fallback symbol set when SCANNER_SYMBOLS is empty.",
    },
    "SCANNER_DATA_SOURCE": {
        "type": str,
        "default": "AUTO",
        "env": ["SCANNER_DATA_SOURCE"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Scanner data provider selection (AUTO/IBKR/MOCK).",
        "choices": ["AUTO", "IBKR", "MOCK"],
        "normalizer": "upper",
    },
    "HISTORICAL_ENRICH_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["HISTORICAL_ENRICH_ENABLED"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Allow historical data enrichment during scanner evaluation.",
    },
    "SCANNER_TOP_GAINERS_COUNT": {
        "type": int,
        "default": 50,
        "env": ["TOP_GAINERS_COUNT"],
        "affects": ["ScannerRunner"],
        "enforcement": "HARD",
        "mutable": "per-cycle",
        "description": "Max symbols requested from scanner provider.",
    },
    "SCANNER_TEACHING_SYMBOL_CAP": {
        "type": int,
        "default": 0,
        "env": ["SCANNER_TEACHING_SYMBOL_CAP"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Cap on symbols per cycle when SCANNER_MODE=TEACHING.",
    },
    "SCANNER_WATCHLIST_LIMIT": {
        "type": int,
        "default": 15,
        "env": [],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "per-cycle",
        "description": "Final watchlist size cap after filtering.",
    },
    "WATCHLIST_PRINT_EVERY_N_CYCLES": {
        "type": int,
        "default": 20,
        "env": ["WATCHLIST_PRINT_EVERY_N_CYCLES"],
        "affects": ["ScannerRunner", "CoreOrchestrator"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Print watchlist/focus lines every N cycles even if unchanged.",
    },
    "SCANNER_SESSION_WINDOWS_UTC": {
        "type": dict,
        "default_factory": _scanner_session_windows_utc,
        "env": [],
        "affects": ["Scanner", "ScannerRunner", "LiveReadOnlyScanner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "UTC hour windows for scanner session labels.",
    },
    "SCANNER_MOCK_SEED": {
        "type": int,
        "default": 42,
        "env": ["SCANNER_MOCK_SEED"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Seed for deterministic mock scanner provider.",
    },
    "SCANNER_MOCK_SYMBOLS_FILE": {
        "type": str,
        "default": "src/scanner/mock_universe.txt",
        "env": ["SCANNER_MOCK_SYMBOLS_FILE"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Path to mock scanner universe symbols.",
    },
    "SCANNER_FLOAT_CACHE_FILE": {
        "type": str,
        "default": "src/scanner/float_cache.json",
        "env": ["SCANNER_FLOAT_CACHE_FILE"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Path to float cache JSON for scanner provider.",
    },
    "SCANNER_VERSION": {
        "type": str,
        "default": "v2026-01-04-11",
        "env": [],
        "affects": ["ScannerRunner"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "Scanner contract/version identifier.",
    },
    "SCANNER_GIT_SHA": {
        "type": str,
        "default": "",
        "env": ["SCANNER_GIT_SHA", "GIT_SHA"],
        "affects": ["ScannerRunner"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Git SHA for scanner build metadata.",
    },
    "SHOW_URLS": {
        "type": bool,
        "default": True,
        "env": ["SHOW_URLS"],
        "affects": ["ScannerMaster"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Enable URL display in scanner output.",
    },
    "DISABLE_OSC8": {
        "type": bool,
        "default": False,
        "env": ["DISABLE_OSC8"],
        "affects": ["ScannerMaster"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Disable OSC-8 hyperlink formatting in scanner output.",
    },
    # =========================
    # Scanner filters (Ross & news)
    # =========================
    "ROSS_MIN_PCT_CHANGE": {
        "type": float,
        "default": 10.0,
        "env": ["ROSS_MIN_PCT_CHANGE"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum percent change for Ross 5 pillars filter.",
    },
    "ROSS_MIN_PRICE": {
        "type": float,
        "default": 1.0,
        "env": ["ROSS_MIN_PRICE"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum price for Ross 5 pillars filter.",
    },
    "ROSS_MAX_PRICE": {
        "type": float,
        "default": 20.0,
        "env": ["ROSS_MAX_PRICE"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Maximum price for Ross 5 pillars filter.",
    },
    "ROSS_MAX_FLOAT": {
        "type": int,
        "default": 20_000_000,
        "env": ["ROSS_MAX_FLOAT"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max float shares for Ross 5 pillars filter.",
    },
    "ROSS_MIN_RVOL": {
        "type": float,
        "default": 5.0,
        "env": ["ROSS_MIN_RVOL"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum relative volume for Ross 5 pillars filter.",
    },
    "ROSS_MIN_VOLUME": {
        "type": int,
        "default": 1_000_000,
        "env": ["ROSS_MIN_VOLUME"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum volume during regular session for Ross filter.",
    },
    "ROSS_MIN_PREMARKET_VOLUME": {
        "type": int,
        "default": 100_000,
        "env": ["ROSS_MIN_PREMARKET_VOLUME"],
        "affects": ["ScannerFilters", "RossMomentum"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum volume during premarket/overnight for Ross filter.",
    },
    "ROSS_REQUIRE_NEWS": {
        "type": bool,
        "default": True,
        "env": ["ROSS_REQUIRE_NEWS"],
        "affects": ["ScannerFilters", "NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Require news headlines to pass Ross 5 pillars filter.",
    },
    "NEWS_MAX_AGE_SECONDS": {
        "type": int,
        "default": 3600,
        "env": ["NEWS_MAX_AGE_SECONDS"],
        "affects": ["ScannerFilters", "NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max age (seconds) for news freshness gates.",
    },
    "NEWS_MIN_VELOCITY_10M": {
        "type": int,
        "default": 1,
        "env": ["NEWS_MIN_VELOCITY_10M"],
        "affects": ["ScannerFilters", "NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum 10-minute news velocity to qualify.",
    },
    "NEWS_MIN_REGIONS": {
        "type": int,
        "default": 1,
        "env": ["NEWS_MIN_REGIONS"],
        "affects": ["ScannerFilters", "NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum region count for news catalyst eligibility.",
    },
    # =========================
    # News ingestion
    # =========================
    "NEWS_ENABLED": {
        "type": bool,
        "default": True,
        "env": ["NEWS_ENABLED"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable RSS news ingestion.",
    },
    "NEWS_LOOKBACK_HOURS": {
        "type": float,
        "default": 6.0,
        "env": ["NEWS_LOOKBACK_HOURS"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Lookback horizon in hours for news matching.",
    },
    "NEWS_MAX_ENTRIES_PER_SYMBOL": {
        "type": int,
        "default": 5,
        "env": ["NEWS_MAX_ENTRIES_PER_SYMBOL"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max news entries retained per symbol.",
    },
    "NEWS_REQUEST_TIMEOUT_S": {
        "type": int,
        "default": 5,
        "env": ["NEWS_REQUEST_TIMEOUT_S"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "HTTP timeout (seconds) for news RSS requests.",
    },
    "VERIFIED_RSS_PATH": {
        "type": str,
        "default_factory": _default_verified_rss_path,
        "env": ["VERIFIED_RSS_PATH"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Path to verified RSS sources list.",
    },
    "NEWS_REFRESH_SECONDS": {
        "type": int,
        "default": 90,
        "env": ["NEWS_REFRESH_SECONDS"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum seconds between RSS refreshes.",
    },
    "NEWS_MAX_ITEMS_PER_FEED": {
        "type": int,
        "default": 75,
        "env": ["NEWS_MAX_ITEMS_PER_FEED"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max RSS entries processed per feed.",
    },
    "NEWS_MAX_TOP_HEADLINES": {
        "type": int,
        "default": 5,
        "env": ["NEWS_MAX_TOP_HEADLINES"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max top headlines included in news context.",
    },
    "NEWS_DEBUG": {
        "type": bool,
        "default": False,
        "env": ["NEWS_DEBUG"],
        "affects": ["NewsEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable verbose news debug logging.",
    },
    # =========================
    # System scheduling & sessions
    # =========================
    "CYCLE_SLEEP_SECONDS": {
        "type": int,
        "default": 3,
        "env": ["CYCLE_SLEEP_SECONDS"],
        "affects": ["CoreOrchestrator"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Sleep interval between orchestrator cycles.",
    },
    "ACTIVE_SESSIONS": {
        "type": list,
        "item_type": str,
        "default": ["PRE", "RTH", "AH"],
        "env": ["ACTIVE_SESSIONS"],
        "affects": ["CoreOrchestrator", "SystemConfig"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Market sessions considered active for safety checks.",
        "normalizer": "upper",
    },
    "SESSION_PHASE_OVERRIDE": {
        "type": str,
        "default": None,
        "env": ["SESSION_PHASE_OVERRIDE"],
        "affects": ["CoreOrchestrator"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Force a market session phase label (e.g., PREMARKET, CLOSED).",
        "normalizer": "upper",
    },
    "MARKET_HOLIDAYS": {
        "type": set,
        "item_type": "date",
        "default": set(),
        "env": ["MARKET_HOLIDAYS"],
        "affects": ["SystemConfig"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Comma-separated list of YYYY-MM-DD market holidays.",
    },
    "MARKET_HALF_DAYS": {
        "type": set,
        "item_type": "date",
        "default": set(),
        "env": ["MARKET_HALF_DAYS"],
        "affects": ["SystemConfig"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Comma-separated list of YYYY-MM-DD half-day sessions.",
    },
    "MARKET_EARLY_CLOSE_TIME": {
        "type": time,
        "default": time(13, 0),
        "env": ["MARKET_EARLY_CLOSE_TIME"],
        "affects": ["SystemConfig"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Early close time for half-day sessions (HH:MM).",
    },
    "MARKET_SESSION_WINDOWS_LOCAL": {
        "type": dict,
        "default_factory": _market_session_windows_local,
        "env": [],
        "affects": ["SystemConfig"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "Local time windows for PRE/REGULAR/AFTER sessions.",
    },
    # =========================
    # Storage & audit
    # =========================
    "PERSISTENCE_ENABLED": {
        "type": bool,
        "default": True,
        "env": ["PERSISTENCE_ENABLED"],
        "affects": ["StorageEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Enable persistence subsystem.",
    },
    "PERSISTENCE_BACKEND": {
        "type": str,
        "default": "sqlite",
        "env": ["PERSISTENCE_BACKEND"],
        "affects": ["StorageEngine"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Persistence backend selection.",
    },
    "PERSISTENCE_SQLITE_PATH": {
        "type": str,
        "default": "data/ibkr_system.db",
        "env": ["PERSISTENCE_SQLITE_PATH"],
        "affects": ["StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "SQLite file path for persistence.",
    },
    "PERSISTENCE_JSONL_MIRROR_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["PERSISTENCE_JSONL_MIRROR_ENABLED"],
        "affects": ["StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable JSONL mirroring alongside SQLite.",
    },
    "AUDIT_HASH_CHAIN_ENABLED": {
        "type": bool,
        "default": True,
        "env": ["AUDIT_HASH_CHAIN_ENABLED"],
        "affects": ["StorageEngine"],
        "enforcement": "HARD",
        "mutable": "static",
        "description": "Enable audit hash chain for stored events.",
    },
    "AUDIT_VERIFY_ON_START": {
        "type": bool,
        "default": False,
        "env": ["AUDIT_VERIFY_ON_START"],
        "affects": ["StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Verify audit chain at startup.",
    },
    "PERSIST_FLUSH_EACH_CYCLE": {
        "type": bool,
        "default": True,
        "env": ["PERSIST_FLUSH_EACH_CYCLE"],
        "affects": ["StorageEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Flush persistence after each cycle.",
    },
    "APP_VERSION": {
        "type": str,
        "default": "UNKNOWN",
        "env": ["APP_VERSION"],
        "affects": ["StorageEngine", "Runtime"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "Application version identifier.",
    },
    "GIT_SHA": {
        "type": str,
        "default_factory": _default_git_sha,
        "env": ["GIT_SHA"],
        "affects": ["StorageEngine", "Runtime"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "Git commit SHA for the running build.",
        "allow_none": True,
    },
    # =========================
    # Risk & execution limits
    # =========================
    "RISK_STRATEGY_LIMITS": {
        "type": dict,
        "default": {
            "SCALPER": {"max_trades": 2},
            "MOMENTUM": {"max_trades": 1},
        },
        "env": [],
        "affects": ["RiskEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Per-trader strategy limits enforced by RiskEngine.",
    },
    "RISK_MAX_POSITION_SIZE": {
        "type": int,
        "default": 1,
        "env": [],
        "affects": ["RiskEngine", "ExecutionEngine"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Max position size allowed by RiskEngine.",
    },
    "RISK_CONFIDENCE_LOW_THRESHOLD": {
        "type": float,
        "default": 0.75,
        "env": [],
        "affects": ["RiskEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Confidence threshold for LOW risk classification.",
    },
    "RISK_CONFIDENCE_MEDIUM_THRESHOLD": {
        "type": float,
        "default": 0.50,
        "env": [],
        "affects": ["RiskEngine"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Confidence threshold for MEDIUM risk classification.",
    },
    "EXECUTION_MAX_ATTEMPTS_BY_TRADER": {
        "type": dict,
        "default": {
            "SCALPER": 2,
            "MOMENTUM": 3,
            "DEFAULT": 1,
        },
        "env": [],
        "affects": ["ExecutionEngine"],
        "enforcement": "SOFT",
        "mutable": "static",
        "description": "Max execution attempts per trader type.",
    },
    "ROSS_RISK_MIN_GAP": {
        "type": float,
        "default": 4.0,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum gap percentage for Ross momentum risk overlay.",
    },
    "ROSS_RISK_MAX_GAP": {
        "type": float,
        "default": 20.0,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Maximum gap percentage for Ross momentum risk overlay.",
    },
    "ROSS_RISK_FLOAT_CEILING": {
        "type": float,
        "default": 100.0,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max float (millions) for Ross momentum overlay.",
    },
    "ROSS_RISK_RVOL_FLOOR": {
        "type": float,
        "default": 2.0,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Min relative volume for Ross momentum overlay.",
    },
    "ROSS_RISK_CONFIDENCE_FLOOR": {
        "type": float,
        "default": 0.60,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Minimum confidence for Ross momentum overlay.",
    },
    "ROSS_RISK_COOLDOWN_TICKS": {
        "type": int,
        "default": 5,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Cooldown ticks after Ross momentum attempt.",
    },
    "ROSS_RISK_MAX_ATTEMPTS_PER_SYMBOL": {
        "type": int,
        "default": 2,
        "env": [],
        "affects": ["RossMomentumRiskOverlay"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Max Ross momentum attempts per symbol.",
    },
    # =========================
    # Strategy governance
    # =========================
    "MIN_HOLD_TICKS": {
        "type": int,
        "default": 2,
        "env": ["MIN_HOLD_TICKS"],
        "affects": ["TradeExitEngine", "Strategies"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Minimum ticks to hold a trade before exit.",
    },
    "MAX_HOLD_TICKS": {
        "type": int,
        "default": 10,
        "env": ["MAX_HOLD_TICKS"],
        "affects": ["TradeExitEngine", "Strategies"],
        "enforcement": "HARD",
        "mutable": "dynamic",
        "description": "Maximum ticks a trade may remain open.",
    },
    "ROSS_MOMENTUM_STRATEGY_ENABLED": {
        "type": bool,
        "default": True,   # default was False
        "env": ["ROSS_MOMENTUM_STRATEGY_ENABLED"],
        "affects": ["Strategies"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable Ross Momentum strategy execution.",
    },
    "STATISTICAL_INTRADAY_MOMENTUM_STRATEGY_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["STATISTICAL_INTRADAY_MOMENTUM_STRATEGY_ENABLED"],
        "affects": ["Strategies"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable Statistical Intraday Momentum strategy execution.",
    },
    "LONG_HORIZON_VALUE_STRATEGY_ENABLED": {
        "type": bool,
        "default": False,
        "env": ["LONG_HORIZON_VALUE_STRATEGY_ENABLED"],
        "affects": ["Strategies"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Enable Long Horizon Value strategy execution.",
    },
    "SELECTED_STRATEGY": {
        "type": str,
        "default": "",
        "env": ["SELECTED_STRATEGY"],
        "affects": ["Strategies"],
        "enforcement": "ADVISORY",
        "mutable": "dynamic",
        "description": "Explicitly selected primary strategy key (CLI override).",
        "normalizer": "lower",
    },
    "ENABLED_STRATEGIES": {
        "type": dict,
        "default": {
            "GapAndGoStrategy": True,
            "MomentumContinuationStrategy": True,
        },
        "env": [],
        "affects": ["Strategies"],
        "enforcement": "ADVISORY",
        "mutable": "dynamic",
        "description": "Strategy allowlist map (name -> enabled).",
    },
    # =========================
    # Translation test inputs (main)
    # =========================
    "IBKR_TRANSLATION_TEST_SYMBOL": {
        "type": str,
        "default": "",
        "env": ["IBKR_TRANSLATION_TEST_SYMBOL"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Optional symbol for IBKR translation dry-run.",
        "normalizer": "upper",
    },
    "IBKR_TRANSLATION_TEST_DIRECTION": {
        "type": str,
        "default": "LONG",
        "env": ["IBKR_TRANSLATION_TEST_DIRECTION"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Direction for IBKR translation dry-run.",
        "normalizer": "upper",
    },
    "IBKR_TRANSLATION_TEST_ORDER_TYPE": {
        "type": str,
        "default": "MKT",
        "env": ["IBKR_TRANSLATION_TEST_ORDER_TYPE"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Order type for IBKR translation dry-run.",
        "normalizer": "upper",
    },
    "IBKR_TRANSLATION_TEST_QUANTITY": {
        "type": int,
        "default": 1,
        "env": ["IBKR_TRANSLATION_TEST_QUANTITY"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Quantity for IBKR translation dry-run.",
    },
    "IBKR_TRANSLATION_TEST_LIMIT_PRICE": {
        "type": float,
        "default": None,
        "env": ["IBKR_TRANSLATION_TEST_LIMIT_PRICE"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Limit price for IBKR translation dry-run.",
        "allow_none": True,
    },
    "IBKR_TRANSLATION_TEST_TIF": {
        "type": str,
        "default": "DAY",
        "env": ["IBKR_TRANSLATION_TEST_TIF"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Time-in-force for IBKR translation dry-run.",
        "normalizer": "upper",
    },
    "IBKR_TRANSLATION_TEST_CLIENT_ORDER_ID": {
        "type": str,
        "default": "dry-run-ibkr-translation",
        "env": ["IBKR_TRANSLATION_TEST_CLIENT_ORDER_ID"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Client order ID for IBKR translation dry-run.",
    },
    "IBKR_TRANSLATION_TEST_STRATEGY_NAME": {
        "type": str,
        "default": "DRY_RUN",
        "env": ["IBKR_TRANSLATION_TEST_STRATEGY_NAME"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Strategy name for IBKR translation dry-run.",
    },
    "IBKR_TRANSLATION_TEST_TRADER_TYPE": {
        "type": str,
        "default": "MANUAL",
        "env": ["IBKR_TRANSLATION_TEST_TRADER_TYPE"],
        "affects": ["CLI", "Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Trader type for IBKR translation dry-run.",
    },
    "IBKR_SMOKE_SYMBOL": {
        "type": str,
        "default": "",
        "env": ["IBKR_SMOKE_SYMBOL"],
        "affects": ["Main"],
        "enforcement": "SOFT",
        "mutable": "dynamic",
        "description": "Symbol for IBKR read-only smoke test.",
        "normalizer": "upper",
    },
    # =========================
    # Future placeholders (explicitly marked)
    # =========================
    "FUTURE_NEWS_SENTIMENT_MODEL": {
        "type": str,
        "default": "PLACEHOLDER",
        "env": ["FUTURE_NEWS_SENTIMENT_MODEL"],
        "affects": ["NewsEngine"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "PLACEHOLDER: sentiment model identifier for future extension.",
    },
    "FUTURE_EXECUTION_RATE_LIMIT": {
        "type": int,
        "default": 0,
        "env": ["FUTURE_EXECUTION_RATE_LIMIT"],
        "affects": ["ExecutionEngine"],
        "enforcement": "ADVISORY",
        "mutable": "dynamic",
        "description": "PLACEHOLDER: per-minute execution rate limit.",
    },
    "FUTURE_STORAGE_RETENTION_DAYS": {
        "type": int,
        "default": 0,
        "env": ["FUTURE_STORAGE_RETENTION_DAYS"],
        "affects": ["StorageEngine"],
        "enforcement": "ADVISORY",
        "mutable": "static",
        "description": "PLACEHOLDER: retention days for stored events.",
    },
}
