"""Centralised event type constants for lifecycle and auditability."""

# Trade lifecycle
TRADE_OPENED = "TRADE_OPENED"
TRADE_CLOSED = "TRADE_CLOSED"

# Shutdown lifecycle
SHUTDOWN_REQUESTED = "SHUTDOWN_REQUESTED"
SHUTDOWN_STARTED = "SHUTDOWN_STARTED"
SHUTDOWN_HOOK_FAILED = "SHUTDOWN_HOOK_FAILED"
SHUTDOWN_COMPLETE = "SHUTDOWN_COMPLETE"
PANIC_STOP_TRIGGERED = "PANIC_STOP_TRIGGERED"
# IBKR submission lifecycle
ORDER_SUBMISSION_ATTEMPTED = "ORDER_SUBMISSION_ATTEMPTED"
ORDER_SUBMITTED_ACK = "ORDER_SUBMITTED_ACK"
ORDER_SUBMISSION_FAILED = "ORDER_SUBMISSION_FAILED"
ORDER_SUBMISSION_BLOCKED = "ORDER_SUBMISSION_BLOCKED"
SIGNALS_GENERATED = "SIGNALS_GENERATED"

__all__ = [
    "TRADE_OPENED",
    "TRADE_CLOSED",
    "SHUTDOWN_REQUESTED",
    "SHUTDOWN_STARTED",
    "SHUTDOWN_HOOK_FAILED",
    "SHUTDOWN_COMPLETE",
    "PANIC_STOP_TRIGGERED",
    "ORDER_SUBMISSION_ATTEMPTED",
    "ORDER_SUBMITTED_ACK",
    "ORDER_SUBMISSION_FAILED",
    "ORDER_SUBMISSION_BLOCKED",
    "SIGNALS_GENERATED",
]
