"""Centralised event type constants for lifecycle and auditability."""

# Trade lifecycle
TRADE_OPENED = "TRADE_OPENED"
TRADE_CLOSED = "TRADE_CLOSED"

# Shutdown lifecycle
SHUTDOWN_REQUESTED = "SHUTDOWN_REQUESTED"
SHUTDOWN_STARTED = "SHUTDOWN_STARTED"
SHUTDOWN_HOOK_FAILED = "SHUTDOWN_HOOK_FAILED"
SHUTDOWN_COMPLETE = "SHUTDOWN_COMPLETE"
PANIC_STOP_TRIGGERED = "PANIC_STOP_TRIGGERED"

__all__ = [
    "TRADE_OPENED",
    "TRADE_CLOSED",
    "SHUTDOWN_REQUESTED",
    "SHUTDOWN_STARTED",
    "SHUTDOWN_HOOK_FAILED",
    "SHUTDOWN_COMPLETE",
    "PANIC_STOP_TRIGGERED",
]
