"""Centralised event type constants for lifecycle and auditability."""

# Trade lifecycle
TRADE_OPENED = "TRADE_OPENED"
TRADE_CLOSED = "TRADE_CLOSED"
TRADE_BLOCKED = "TRADE_BLOCKED"
PROTECTIVE_STOP_PLACED = "PROTECTIVE_STOP_PLACED"
TRADE_STATE_UPDATED = "TRADE_STATE_UPDATED"
EXIT_STOP_LOSS = "EXIT_STOP_LOSS"
EXIT_TIME = "EXIT_TIME"
EXIT_TARGET = "EXIT_TARGET"
EXIT_FAILED_SETUP = "EXIT_FAILED_SETUP"
EXIT_STRATEGY = "EXIT_STRATEGY"

# Shutdown lifecycle
SHUTDOWN_REQUESTED = "SHUTDOWN_REQUESTED"
SHUTDOWN_STARTED = "SHUTDOWN_STARTED"
SHUTDOWN_HOOK_FAILED = "SHUTDOWN_HOOK_FAILED"
SHUTDOWN_COMPLETE = "SHUTDOWN_COMPLETE"
PANIC_STOP_TRIGGERED = "PANIC_STOP_TRIGGERED"
# IBKR submission lifecycle
ORDER_SUBMISSION_ATTEMPTED = "ORDER_SUBMISSION_ATTEMPTED"
ORDER_SUBMITTED_ACK = "ORDER_SUBMITTED_ACK"
ORDER_SUBMISSION_FAILED = "ORDER_SUBMISSION_FAILED"
ORDER_SUBMISSION_BLOCKED = "ORDER_SUBMISSION_BLOCKED"
ORDER_FILL_RECORDED = "ORDER_FILL_RECORDED"
SIGNALS_GENERATED = "SIGNALS_GENERATED"
CIRCUIT_BREAKER_TRIGGERED = "CIRCUIT_BREAKER_TRIGGERED"

__all__ = [
    "TRADE_OPENED",
    "TRADE_CLOSED",
    "TRADE_BLOCKED",
    "PROTECTIVE_STOP_PLACED",
    "TRADE_STATE_UPDATED",
    "EXIT_STOP_LOSS",
    "EXIT_TIME",
    "EXIT_TARGET",
    "EXIT_FAILED_SETUP",
    "EXIT_STRATEGY",
    "SHUTDOWN_REQUESTED",
    "SHUTDOWN_STARTED",
    "SHUTDOWN_HOOK_FAILED",
    "SHUTDOWN_COMPLETE",
    "PANIC_STOP_TRIGGERED",
    "ORDER_SUBMISSION_ATTEMPTED",
    "ORDER_SUBMITTED_ACK",
    "ORDER_SUBMISSION_FAILED",
    "ORDER_SUBMISSION_BLOCKED",
    "ORDER_FILL_RECORDED",
    "SIGNALS_GENERATED",
    "CIRCUIT_BREAKER_TRIGGERED",
]
