from src.strategy_policy_v2.policy_v2 import (
    C_VOLATILITY_NON_AUTHORITATIVE,
    ConfirmationSpecV2,
    DataRequirementsV2,
    ExecutionModelV2,
    ExitModelV2,
    ExitRuleV2,
    IntentContractV2,
    LongHorizonPortfolioConstraintsV2,
    LongHorizonUnderwritingBatchModelV2,
    LongHorizonCapitalAllocationModelV2,
    LongHorizonValuationScenarioModelV2,
    LongHorizonMonitoringModelV2,
    LongHorizonRebalanceModelV2,
    LongHorizonThesisModelV2,
    LongHorizonValuationModelV2,
    IntrabarCadenceRuleV2,
    IntrabarExecutionModelV2,
    IntrabarPhaseSpecV2,
    IntrabarSafetyThrottleV2,
    IntrabarTimeframeMapV2,
    LiquiditySanityModelV2,
    ModeSemanticsV2,
    PatternCatalogV2,
    PatternSpecV2,
    PositionManagementV2,
    PremarketFilterSpecV2,
    PremarketLevelSpecV2,
    PremarketPreparationModelV2,
    RankingModelV2,
    RiskModelV2,
    SafetyModelV2,
    SafetyRuleV2,
    SessionReferenceLawV2,
    SessionSemanticsV2,
    SetupFamiliesV2,
    SetupFamilySpecV2,
    StrategyIdentityV2,
    StrategyPolicyV2,
    StructureModelV2,
    TrailingModelV2,
    TrailingRuleV2,
    TriggerEntrySpecV2,
    TriggerModelV2,
)
from src.strategy_policy_v2.selection_plans import PortfolioPlan


POLICY_V2 = StrategyPolicyV2(
    identity=StrategyIdentityV2(name="LONG_HORIZON_VALUE", strategy_id="P04"),
    selection_plan=PortfolioPlan(
        universe_source="FUNDAMENTAL_UNIVERSE",
        rebalance_frequency="MONTHLY",
        target_count=20,
    ),
    mode_semantics=ModeSemanticsV2(
        sim_notes="SIM executes full policy gates and emits auditable decision artifacts.",
        paper_notes="PAPER mode mirrors SIM policy behavior with broker-safe intent output.",
        read_only_notes="READ_ONLY runs selection, setup, and risk evaluation but blocks executable intents.",
        live_notes="LIVE is permitted only when this policy and risk envelope are wired by runtime governance.",
    ),
    session_semantics=SessionSemanticsV2(
        sessions=("PRE", "RTH", "AH", "OVN", "CLOSED"),
        market_closed_semantics="CLOSED session blocks new entries and forces only risk-reducing actions.",
    ),
    risk_model=RiskModelV2(
        max_position_pct=0.08,
        daily_loss_limit=0.018,
        max_open_positions=6,
        notes=(
            "Long-horizon risk doctrine prioritizes permanent capital impairment, leverage fragility, concentration limits, and thesis break risk. "
            f"{C_VOLATILITY_NON_AUTHORITATIVE}: daily_loss_limit remains platform-envelope metadata for interoperability "
            "and is non-authoritative for P04 exits, which are thesis/valuation driven under governance constraints."
        ),
    ),
    execution_model=ExecutionModelV2(
        preferred_order_types=("LIMIT", "STOP_LIMIT"),
        allow_market_orders=False,
        allow_extended_hours=True,
        notes="D6 trigger execution doctrine is explicit and traceable with slippage-aware controls.",
    ),
    intent_contract=IntentContractV2(
        emitted_intents=("DECISION_INTENT", "TRADE_INTENT", "RISK_DECISION"),
        emitted_artifacts=("strategy_decision", "setup_evaluation", "risk_snapshot", "exit_decision"),
        notes="D13 monitoring: trace_id and setup_family_id are mandatory in every emitted artifact.",
    ),
    setup_families=SetupFamiliesV2(
        families=(
            SetupFamilySpecV2("MOAT_COMPOUNDER_ACCUMULATION", "Moat Compounder Accumulation", "Accumulate understandable high-quality compounders when valuation offers margin of safety.", ("DAILY", "WEEKLY", "MONTHLY")),
            SetupFamilySpecV2("QUALITY_AT_FAIR_PRICE", "Quality at Fair Price", "Initiate or hold quality businesses near fair value with disciplined underwriting.", ("DAILY", "WEEKLY", "MONTHLY")),
            SetupFamilySpecV2("DEEP_VALUE_MARGIN_OF_SAFETY", "Deep Value Margin of Safety", "Require explicit discount to intrinsic value with balance-sheet resilience and catalyst path.", ("DAILY", "WEEKLY", "MONTHLY")),
            SetupFamilySpecV2("TEMPORARY_HEADWIND_DISLOCATION", "Temporary Headwind Dislocation", "Adverse headlines are tolerated only when thesis and fundamentals remain intact.", ("DAILY", "WEEKLY", "MONTHLY")),
            SetupFamilySpecV2("CAPITAL_ALLOCATION_UPGRADE", "Capital Allocation Upgrade", "Management demonstrates disciplined buybacks, reinvestment, and shareholder-oriented actions.", ("DAILY", "WEEKLY", "MONTHLY")),
            SetupFamilySpecV2("SPECIAL_SITUATION", "Special Situation", "Policy-explicit carve-out for deterministic value realization catalysts.", ("DAILY", "WEEKLY", "MONTHLY")),
        )
    ),
    pattern_catalog=PatternCatalogV2(
        patterns=(
            PatternSpecV2("PATTERN_MOAT_EVIDENCE", "Moat Evidence Persistence", "MULTI_CANDLE", "Tracks pricing power, retention, and competitive durability evidence."),
            PatternSpecV2("PATTERN_VALUATION_DISCOUNT", "Valuation Discount Regime", "EXECUTION", "Tracks discount/premium relative to intrinsic value and fair-value bands."),
            PatternSpecV2("PATTERN_THESIS_IMPAIRMENT", "Thesis Impairment Signal", "RISK", "Captures durable disconfirming evidence requiring trim/exit actions."),
        )
    ),
    trigger_model=TriggerModelV2(
        entries=(
            TriggerEntrySpecV2("T_BUY_MOS_BAND", "VALUATION_THESIS", "MOS is in buy band and thesis confirmations pass.", ("PRE", "RTH", "AH", "OVN")),
            TriggerEntrySpecV2("T_ADD_ON_DIP_WITHIN_THESIS", "VALUATION_THESIS", "Position exists, fundamentals remain intact, and MOS improves into add band.", ("PRE", "RTH", "AH", "OVN")),
            TriggerEntrySpecV2("T_HOLD_MONITOR", "VALUATION_THESIS", "Price remains within fair-value hold band with no thesis impairment.", ("PRE", "RTH", "AH", "OVN")),
            TriggerEntrySpecV2("T_TRIM_OVERVALUED", "VALUATION_THESIS", "Price enters premium band versus intrinsic value and trim discipline is enabled.", ("PRE", "RTH", "AH", "OVN")),
            TriggerEntrySpecV2("T_EXIT_THESIS_BREAK", "THESIS_RISK", "Disconfirming evidence indicates thesis break or permanent impairment risk.", ("PRE", "RTH", "AH", "OVN")),
        ),
        confirmations=(
            ConfirmationSpecV2("C_BUSINESS_UNDERSTANDABILITY", "Business model remains inside circle of competence and underwriting scope."),
            ConfirmationSpecV2("C_MOAT_EVIDENCE", "Moat evidence persists and moat erosion signals are below policy thresholds."),
            ConfirmationSpecV2("C_MANAGEMENT_CAPITAL_ALLOCATION", "Management capital-allocation discipline remains aligned with shareholder value compounding."),
            ConfirmationSpecV2("C_ACCOUNTING_QUALITY", "Accounting quality checks pass with no manipulation/restatement red flags."),
            ConfirmationSpecV2("C_BALANCE_SHEET_STRENGTH", "Leverage and coverage metrics remain inside policy limits for resilience."),
            ConfirmationSpecV2("C_VALUATION_METHOD_VALIDITY", "Valuation method is valid for the business model and tie-breaker law is satisfied."),
            ConfirmationSpecV2("C_FUNDAMENTAL_DATA_FRESHNESS", "Fundamental and valuation inputs are current enough for long-horizon authority."),
            ConfirmationSpecV2("C_EXECUTION_CONTEXT_ONLY", "pct_change/volume/rvol/spread/session fields are used only for execution context and never primary thesis decisions."),
            ConfirmationSpecV2("C_UNDERWRITING_SESSION_GUARD", "Underwriting-heavy batch processing and BUY/ADD decision authority are vetoed during RTH and restricted to CLOSED/OVN governance windows."),
            ConfirmationSpecV2("C_MANUAL_APPROVAL_REQUIRED", "BUY and ADD actions require explicit manual approval by default before intent execution."),
            ConfirmationSpecV2("C_SCENARIO_CONSERVATIVE_INTRINSIC", "Intrinsic value used for MOS must default to conservative scenario output (min/BEAR) unless adjudication evidence is documented."),
            ConfirmationSpecV2("C_THESIS_HEALTH_GATE", "New entry authority requires thesis health GREEN unless a governance-approved exception is explicitly recorded."),
        ),
    ),
    session_reference_law=SessionReferenceLawV2(
        pct_change_reference="Percent-change references prior close for cross-session continuity.",
        gap_reference="Gap references session open versus prior close for opening context only.",
        closed_session_preparation_notes="Closed-session preparation updates selection and risk tiers before next open.",
    ),
    structure_model=StructureModelV2(
        levels=("PM_HIGH", "PM_LOW", "VWAP", "DAY_HIGH", "DAY_LOW"),
        zones=("VALUE_AREA", "OPENING_RANGE", "IMBALANCE_ZONE"),
        notes="D3/D4 structure authority for level interaction and confirmation behavior.",
    ),
    position_management=PositionManagementV2(
        allow_scale_in=True,
        max_adds_per_position=2,
        allow_partials=True,
        averaging_down_allowed=False,
        notes="D8 scaling doctrine: add only with cushion and renewed confirmation; no averaging down.",
    ),
    trailing_model=TrailingModelV2(
        rules=(
            TrailingRuleV2("TRAIL_STRUCTURE", "New higher-low / lower-high prints", "Trail stop to invalidation structure."),
        )
    ),
    long_horizon_thesis=LongHorizonThesisModelV2(
        business_quality_requirements=(
            "Business economics are understandable within circle of competence.",
            "Durable returns on capital and cash generation are evidenced across cycles.",
            "Unit economics and reinvestment runway support long-term compounding.",
        ),
        moat_taxonomy=(
            "Network effects",
            "Cost advantage",
            "Intangible assets/brand",
            "Switching costs",
            "Efficient scale",
        ),
        management_capital_allocation_checks=(
            "Buybacks executed below intrinsic value and not merely anti-dilutive.",
            "Dividend and reinvestment policy balance compounding and resilience.",
            "M&A discipline favors returns over empire-building behavior.",
            "SBC and dilution are controlled relative to value creation.",
        ),
        disconfirming_signals=(
            "Moat erosion with persistent share/price-power deterioration.",
            "Governance deterioration, accounting quality concerns, or restatements.",
            "Capital-allocation drift toward value-destructive actions.",
            "Balance-sheet weakening that impairs survivability under stress.",
        ),
        monitoring_cadence="Monthly monitoring with quarterly deep-dive after financial updates; event-driven reviews on material thesis events.",
        notes="Thesis model is the primary decision authority for BUY/ADD/HOLD/TRIM/EXIT in P04.",
    ),
    long_horizon_valuation=LongHorizonValuationModelV2(
        primary_methods=(
            "Discounted cash flow",
            "Owner earnings yield versus required return",
            "Normalized earnings multiple anchored to quality/regime",
            "Sum-of-the-parts when conglomerate structure is material",
        ),
        underwriting_horizon_years=5,
        required_return_floor=0.15,
        tie_breaker_law="When methods disagree, use the most conservative intrinsic value estimate unless explicit adjudication evidence supports otherwise.",
        margin_of_safety_bands=(
            "Strong buy MOS: >= 30% discount",
            "Add MOS: 20%-30% discount with intact thesis",
            "Hold band: within ±10% of fair value",
            "Trim band: 10%-25% premium",
            "Exit valuation band: >25% premium absent superior growth revision",
        ),
        action_bands=(
            "BUY: T_BUY_MOS_BAND when MOS and thesis confirmations pass.",
            "ADD: T_ADD_ON_DIP_WITHIN_THESIS with improved MOS and no new disconfirming signals.",
            "HOLD: T_HOLD_MONITOR while valuation is near fair value and thesis remains intact.",
            "TRIM: T_TRIM_OVERVALUED as premium emerges.",
            "EXIT: T_EXIT_THESIS_BREAK or extreme premium with weak forward asymmetry.",
        ),
        notes="Valuation validity is mandatory; no new entry without intrinsic value and MOS evidence.",
    ),
    long_horizon_rebalance=LongHorizonRebalanceModelV2(
        review_frequency="MONTHLY",
        fundamentals_refresh_frequency="QUARTERLY",
        turnover_cap_per_review=0.20,
        minimum_holding_period_days=180,
        event_driven_review_triggers=(
            "Earnings release materially diverges from underwriting.",
            "Guidance reset or thesis-critical KPI breakdown.",
            "Credit rating change or refinancing stress signal.",
            "Major capital-allocation event (large M&A, buyback suspension, dividend cut).",
            "Accounting restatement, fraud allegation, or governance shock.",
        ),
        notes="Rebalance discipline limits churn and enforces long-horizon holding behavior.",
    ),
    long_horizon_portfolio_constraints=LongHorizonPortfolioConstraintsV2(
        max_single_position_pct=0.08,
        max_new_allocation_pct=0.03,
        sector_caps=(
            "No sector above 30% of total portfolio market value.",
            "No single thematic bucket above 40% when mapped upstream.",
        ),
        cash_buffer_rule="Maintain strategic cash buffer between 5%-15% unless broad MOS opportunity set is exceptional and documented.",
        notes="Sector caps may be computed upstream; policy still declares the governing law for auditability.",
    ),
    long_horizon_underwriting_batch=LongHorizonUnderwritingBatchModelV2(
        allowed_sessions=("CLOSED", "OVN"),
        forbid_sessions=("RTH",),
        batch_window_policy="Run heavy underwriting only when market is closed to avoid interfering with trading runtime; weekends and off-session windows are allowed, and RTH underwriting is prohibited.",
        universe_traversal_law="Traverse universe deterministically by stable symbol ordering with cached fundamentals; refresh stale issuer packets on scheduled CLOSED/OVN cadence before final ranking pass.",
        output_artifacts=("underwriting_dossier", "watchlist_snapshot", "rejections_log"),
        manual_approval_required_for=("BUY", "ADD"),
        notes="Option B doctrine: closed-session underwriting batch produces curated watchlist; execution remains gated by explicit human approval.",
    ),
    long_horizon_capital_allocation=LongHorizonCapitalAllocationModelV2(
        conviction_tiers=("A", "B", "C"),
        tier_target_weights={"A": 0.08, "B": 0.05, "C": 0.03},
        tranche_entry_law="MOS ladder: BUY when MOS >=30%; ADD in 20%-30% MOS band with intact thesis and health GREEN; HOLD near fair value; TRIM when premium emerges; EXIT on thesis break or persistent impairment evidence.",
        cash_deployment_law="Deploy cash buffer incrementally into highest-conviction names only after CLOSED/OVN underwriting refresh confirms MOS and thesis health; preserve strategic cash floor outside broad dislocation regimes.",
        correlation_exposure_law="Constrain sector/theme clustering so incremental adds do not violate sector caps or concentrate correlated thesis risk beyond policy tolerance.",
        notes="Tier sizing respects max_single_position_pct=0.08 and max_new_allocation_pct=0.03 via staged tranches and governance gating.",
    ),
    long_horizon_valuation_scenarios=LongHorizonValuationScenarioModelV2(
        scenarios=("BASE", "BEAR", "BULL"),
        discount_rate_policy="Required-return doctrine uses bounded discount rates consistent with business durability and balance-sheet risk; apply higher hurdle under leverage, cyclicality, or governance uncertainty.",
        terminal_value_policy="Terminal assumptions must remain conservative: bounded terminal growth, sanity-checked multiples, and no terminal value dominance without explicit justification.",
        competitive_advantage_period_policy="Set explicit CAP horizon with fade dynamics from excess returns toward normalized economics; shorten CAP when moat durability evidence weakens.",
        sensitivity_grid_policy="Run deterministic sensitivity grid across revenue growth, margin trajectory, reinvestment intensity, discount rate, CAP length, and terminal assumptions; preserve scenario traceability in artifacts.",
        conservatism_law="Use conservative intrinsic value for MOS (minimum scenario output or BEAR case) unless adjudication evidence is recorded and approved.",
        notes="Scenario surface formalizes valuation uncertainty management while preserving auditability.",
    ),
    long_horizon_monitoring=LongHorizonMonitoringModelV2(
        kpi_watchlist=(
            "Revenue trajectory",
            "Gross margin",
            "Operating margin",
            "Free cash flow and FCF margin",
            "ROIC/ROCE durability",
            "Leverage and interest-coverage resilience",
            "Dilution, buybacks, and SBC discipline",
            "Governance/accounting red flags",
        ),
        review_cadence="Monthly KPI review with quarterly deep-dive underwriting refresh; event-driven escalation on thesis-critical updates.",
        thesis_health_bands=("GREEN", "YELLOW", "RED"),
        escalation_actions=(
            "YELLOW: pause new adds, increase monitoring frequency, and document remediation conditions.",
            "RED: suspend entry authority and execute trim/exit pathway unless explicit governance exception is approved.",
        ),
        notes="Entry authority is health-gated: GREEN by default, with explicit exception workflow for deviations.",
    ),
    exit_model=ExitModelV2(
        rules=(
            ExitRuleV2("EXIT_THESIS_BREAK", "Core thesis is impaired or disconfirming signals breach policy tolerance.", "Exit full position immediately"),
            ExitRuleV2("EXIT_MOAT_EROSION", "Moat erosion evidence becomes persistent and non-transient.", "Exit full position or cut to monitoring residual"),
            ExitRuleV2("EXIT_ACCOUNTING_RESTATEMENT_FRAUD", "Accounting restatement, fraud signal, or manipulation risk is elevated.", "Exit full position and suspend re-entry pending recertification"),
            ExitRuleV2("EXIT_LEVERAGE_DETERIORATION", "Leverage/coverage metrics deteriorate beyond policy thresholds.", "De-risk aggressively or exit fully based on severity"),
            ExitRuleV2("TRIM_VAL_PREMIUM_BAND", "Valuation enters premium/overvalued band versus intrinsic value.", "Trim systematically according to valuation ladder"),
            ExitRuleV2("EXIT_EXTREME_OVERVALUATION", "Valuation reaches extreme premium with weak forward return asymmetry.", "Exit remaining exposure unless explicit exception is documented"),
            ExitRuleV2("OPPORTUNITY_COST_SWITCH", "Higher-conviction opportunity exists with better MOS and stronger thesis fit.", "Switch only within turnover cap and minimum-holding-period policy"),
        )
    ),
    safety_model=SafetyModelV2(
        rules=(
            SafetyRuleV2("HALT_GUARD", "Volatility halt or regulatory pause", "Block new orders until tradability recertified"),
            SafetyRuleV2("DATA_DEGRADATION", "Delayed or missing core feed fields", "Pause entries and reject stale signals"),
            SafetyRuleV2("LOSS_STREAK", "Two consecutive full-risk losses", "Escalate and reduce size tier"),
            SafetyRuleV2("MODEL_DISAGREEMENT", "Setup family and regime gates disagree", "Mandatory no-trade decision"),
        )
    ),
    liquidity_sanity_model=LiquiditySanityModelV2(
        spread_max_pct=0.8,
        halt_policy="If halted or reopening auction is unstable, reject entries until stability checks pass.",
        ssr_handling="On SSR pressure, short-side actions are blocked and long-side size is reduced.",
        execution_feasibility_commentary="Execution feasibility must pass before trigger-to-order transition.",
        calibration_notes="Thresholds are governance defaults pending replay calibration.",
    ),
    ranking_model=RankingModelV2(
        weight_pct_change=0.05,
        weight_rvol=0.05,
        weight_float_inverse=0.0,
        weight_catalyst=0.15,
        liquidity_penalty=0.05,
        ranking_commentary="Long-horizon ranking is primarily conviction-weighted by thesis durability, business quality, and valuation/MOS; microstructure fields are secondary execution-context inputs only.",
        calibration_notes="Momentum and participation inputs are intentionally de-emphasized for long-horizon value policy semantics.",
    ),
    data_requirements=DataRequirementsV2(
        required_fields=("symbol", "last_price", "pct_change", "volume", "rvol", "spread_bps", "session_phase", "halt_status"),
        optional_fields=(
            "news_catalyst",
            "float_shares",
            "short_interest_pct",
            "borrow_rate",
            "regime_tag",
            "revenue",
            "revenue_cagr_5y",
            "gross_margin",
            "operating_margin",
            "fcf",
            "fcf_margin",
            "roic",
            "roce",
            "debt_to_ebitda",
            "interest_coverage",
            "net_debt",
            "share_count",
            "dilution_rate",
            "buyback_amount",
            "sbc",
            "earnings_quality_flags",
            "restatement_flag",
            "intrinsic_value_estimate",
            "valuation_method",
            "mos_pct",
            "fair_value_low",
            "fair_value_high",
            "valuation_scenario_base",
            "valuation_scenario_bear",
            "valuation_scenario_bull",
            "discount_rate_assumption",
            "terminal_value_assumption",
            "competitive_advantage_period_years",
        ),
        notes="D10 governance: required_fields retain cross-strategy audit compliance (symbol, last_price, and pct_change|volume|rvol) for interoperability. For P04 these are execution/context-only and never primary decision drivers. Missing intrinsic_value_estimate, valuation_method, mos_pct, or fair-value band fields mandates REJECT for new entries. Missing core financial-strength fields (revenue trajectory, profitability, FCF, leverage, and coverage set) mandates REJECT for new entries. DEGRADE authority is allowed only for managing already-open positions while remediation is in progress.",
    ),
    premarket_preparation=PremarketPreparationModelV2(
        required_levels=(
            PremarketLevelSpecV2("PM_HIGH", "Premarket high for breakout context."),
            PremarketLevelSpecV2("PM_LOW", "Premarket low for invalidation anchoring."),
        ),
        required_filters=(
            PremarketFilterSpecV2("LIQUIDITY", "Liquidity threshold must be satisfied."),
            PremarketFilterSpecV2("EXECUTABILITY", "Spread and tape quality must be executable."),
        ),
        optional_filters=(PremarketFilterSpecV2("CATALYST", "Catalyst confidence improves ranking priority.", required=False),),
        room_to_run_policy="D2 universe law requires room-to-run relative to nearby structure.",
        notes="D3 conditions and D4 confirmations are preflighted before session handoff.",
    ),
    intrabar_execution=IntrabarExecutionModelV2(
        phase_specs=(
            IntrabarPhaseSpecV2("INTRABAR_POLICY", "Intrabar Doctrine", "NOT_APPLICABLE", "Intrabar controls are explicitly declared."),
        ),
        timeframe_map=(
            IntrabarTimeframeMapV2(
                "INTRABAR_POLICY",
                ("5MIN", "1MIN"),
                ("5MIN", "1MIN"),
                ("10SEC", "1MIN") if "NOT_APPLICABLE" == "APPLICABLE" else ("1MIN", "5MIN"),
                "Intrabar exits may override candle close." if "NOT_APPLICABLE" == "APPLICABLE" else "NOT_APPLICABLE for intrabar override; candle-close authority only.",
            ),
        ),
        cadence_rules=(IntrabarCadenceRuleV2("CADENCE_CONTROL", ("INTRABAR_POLICY",), "Cadence adapts to liquidity and volatility regime."),),
        safety_throttles=(IntrabarSafetyThrottleV2("THROTTLE_NEWS", "Unscheduled news shock", "Throttle entries for cooling interval."),),
        setup_family_relationship="D12 authority is explicitly bound to setup family execution semantics.",
        notes="D14 constraints: implicit defaults are prohibited; every executable behavior is declared.",
    ),
    notes="Institutional Matrix V2 declaration includes D0 through D14 with explicit governance sections.",
)
