"""Shared setup family implementations."""

from src.setup_engine.setup_families.breakouts import (
    ConsolidationBreakoutPattern,
    OpeningRangeBreakoutPattern,
    PremarketHighBreakPattern,
)
from src.setup_engine.setup_families.momentum import BullFlagPattern, MicroPullbackPattern
from src.setup_engine.setup_families.placeholders import (
    ClimaxTopPattern,
    EngulfingPattern,
    LongUpperWickPattern,
    MarubozuPattern,
    ThreeSoldiersCrowsPattern,
    VolumeClimaxPattern,
)
from src.setup_engine.setup_families.pullbacks import (
    AscendingTriangleBreakoutPattern,
    EmaPullbackPattern,
    FlatTopBreakoutPattern,
    HODBreakPattern,
    LiquiditySweepReclaimPattern,
    OpeningDrivePattern,
    PennantBreakPattern,
    RangeBreakoutPattern,
    SecondPullbackPattern,
    ThreeBarPullbackPattern,
    TrendContinuationStairStepPattern,
    VwapPullbackPattern,
)
from src.setup_engine.setup_families.reversals import FailedBreakoutPattern
from src.setup_engine.setup_families.ross_families import (
    ABCDPattern,
    CupHandlePattern,
    FailedOrbFakeoutPattern,
    FirstPullbackPattern,
    GapFillReversalPattern,
    GapGoPattern,
    HaltResumePattern,
    KeyLevelBreakPattern,
    MomentumReclaimPattern,
    OpeningFakeoutPattern,
    ParabolicExhaustionPattern,
)

__all__ = [
    "ABCDPattern",
    "AscendingTriangleBreakoutPattern",
    "BullFlagPattern",
    "ClimaxTopPattern",
    "ConsolidationBreakoutPattern",
    "CupHandlePattern",
    "EmaPullbackPattern",
    "EngulfingPattern",
    "FailedBreakoutPattern",
    "FailedOrbFakeoutPattern",
    "FirstPullbackPattern",
    "FlatTopBreakoutPattern",
    "GapFillReversalPattern",
    "GapGoPattern",
    "HODBreakPattern",
    "HaltResumePattern",
    "KeyLevelBreakPattern",
    "LiquiditySweepReclaimPattern",
    "LongUpperWickPattern",
    "MarubozuPattern",
    "MicroPullbackPattern",
    "MomentumReclaimPattern",
    "OpeningDrivePattern",
    "OpeningFakeoutPattern",
    "OpeningRangeBreakoutPattern",
    "ParabolicExhaustionPattern",
    "PennantBreakPattern",
    "PremarketHighBreakPattern",
    "RangeBreakoutPattern",
    "SecondPullbackPattern",
    "ThreeBarPullbackPattern",
    "ThreeSoldiersCrowsPattern",
    "TrendContinuationStairStepPattern",
    "VolumeClimaxPattern",
    "VwapPullbackPattern",
]
