"""Risk decision reason codes used for deterministic blocks."""

ROSS_BLOCK_SHORT = "ROSS_BLOCK_SHORT"
ROSS_BLOCK_GAP_OUT_OF_RANGE = "ROSS_BLOCK_GAP_OUT_OF_RANGE"
ROSS_BLOCK_FLOAT_TOO_HIGH = "ROSS_BLOCK_FLOAT_TOO_HIGH"
ROSS_BLOCK_LOW_RVOL = "ROSS_BLOCK_LOW_RVOL"
ROSS_BLOCK_LOW_CONFIDENCE = "ROSS_BLOCK_LOW_CONFIDENCE"
ROSS_BLOCK_COOLDOWN_ACTIVE = "ROSS_BLOCK_COOLDOWN_ACTIVE"
ROSS_BLOCK_MAX_ATTEMPTS = "ROSS_BLOCK_MAX_ATTEMPTS"
STRATEGY_LIMIT_REACHED = "STRATEGY_LIMIT_REACHED"
DATA_QUALITY_BLOCK = "DATA_QUALITY_BLOCK"
EXECUTION_DISABLED = "EXECUTION_DISABLED"
LIVE_READ_ONLY_BLOCK = "LIVE_READ_ONLY_BLOCK"
BROKER_READONLY_BLOCK = "BROKER_READONLY_BLOCK"
STRATEGY_READ_ONLY_EXECUTION_LOCK = "STRATEGY_READ_ONLY_EXECUTION_LOCK"
DUPLICATE_INTENT_ID = "DUPLICATE_INTENT_ID"
INTENT_MISSING_FIELDS = "INTENT_MISSING_FIELDS"
SESSION_CLOSED = "SESSION_CLOSED"
RISK_MAX_OPEN_POSITIONS = "RISK_MAX_OPEN_POSITIONS"
RISK_MAX_TOTAL_EXPOSURE = "RISK_MAX_TOTAL_EXPOSURE"
RISK_MAX_RISK_PER_TRADE = "RISK_MAX_RISK_PER_TRADE"

__all__ = [
    "ROSS_BLOCK_SHORT",
    "ROSS_BLOCK_GAP_OUT_OF_RANGE",
    "ROSS_BLOCK_FLOAT_TOO_HIGH",
    "ROSS_BLOCK_LOW_RVOL",
    "ROSS_BLOCK_LOW_CONFIDENCE",
    "ROSS_BLOCK_COOLDOWN_ACTIVE",
    "ROSS_BLOCK_MAX_ATTEMPTS",
    "STRATEGY_LIMIT_REACHED",
    "DATA_QUALITY_BLOCK",
    "EXECUTION_DISABLED",
    "LIVE_READ_ONLY_BLOCK",
    "BROKER_READONLY_BLOCK",
    "STRATEGY_READ_ONLY_EXECUTION_LOCK",
    "DUPLICATE_INTENT_ID",
    "INTENT_MISSING_FIELDS",
    "SESSION_CLOSED",
    "RISK_MAX_OPEN_POSITIONS",
    "RISK_MAX_TOTAL_EXPOSURE",
    "RISK_MAX_RISK_PER_TRADE",
]
